


<table border="0" style="width: 765px">
	<tr>
		<td title="Limpieza"  class= "heather" id="tit2" colSpan="3" height="20">FRANQUICIAS DISPONIBLES EN EN TODAS LAS COMUNIDADES UNASE A NUESTRO EQUIPO</td>

	</tr>
	<tr>
		<td title="Limpieza"  id="img" vAlign="center" colspan="" style="width: 327px">
			<a href="http://www.foxclean.es"><IMG height="57" hspace="5" src="foxclean1.JPG" width="228" border="0"/></a>
		</td>
		<td title="Limpieza"  height="65" align="left" colspan="" rowspan="" style="width: 220px">
			<A href="Presupuestos.aspx">
				<IMG height="48" hspace="5" src="quote.gif" width="228" border="0"/>
			</A>
		</td>
		<td title="Limpieza"  height="18" style="width: 118px">
<!-- Live2support.com tracking codes starts --><div id="l2s_trk" style="z-index:99;"><a href="http://live2support.com" style="size:1px;">Live Help</a></div><script type="text/javascript"><!-- 
var l2s_lang='2743';var l2sinvite='Y'; var l2sinvwin='fw'; var l2sdly='60'; var l2sitop='center'; var l2sileft='center'; var l2s_pht=escape(location.protocol); if(l2s_pht.indexOf("http")==-1) l2s_pht='http:';  var off2="http://www.foxclean.us/fotos/offline2.gif"; var on2="http://www.foxclean.us/fotos/online2.gif"; var dept="0"; function l2s_load() { document.write('<scr'+'ipt type="text/javascr'+'ipt" src ="'+unescape(l2s_pht)+'//live2support.com/js/lsjs1.php?stid=11990&cmi=1"  defer=true>'+'</scr'+'ipt>');  } 
l2s_load();  document.getElementById('l2s_trk').style.visibility='hidden'; //--></script><!-- Live2support.com tracking codes closed -->

		</td>
	</tr>
	<tr>
		<td title="Limpieza"  nowrap="" id="fon" vAlign="center" style="width: 327px">Telefono Gratuito : 900 606 900</td>
		<td title="Limpieza"  nowrap="" height="18" class="datos" align ="center" style="width: 230px;" colspan="2">
			E-MAIL: <A href="mailto:admin@foxclean.net">admin@foxclean.net</A>
		</td>

	</tr>
</table>