<div id="pri-nav" align ="center">
  <ul>
    
    <li class="nav-top-2">
      <a href="index.aspx">Inicio</a>

    </li>
    <li class="nav-top-1"><a>Servicios</a>
      
      <ul>
        <li class="nav-top-1"><a href="limpieza.aspx">Limpieza para oficinas.</a></li>  
        <li class="nav-top-1"><a href="comunidades.aspx">Limpieza para comunidades.</a></li> 
        <li class="nav-top-1"><a href="ventanas.aspx">Limpieza de cristales.</a></li> 
         <li class="nav-top-1"><a href="conductos.aspx">Limpieza de conductos.</a></li> 
         <li class="nav-top-1"><a href="PestControl.aspx">Servicio de pest-control.</a></li> 
        <li class="nav-top-1"><a href="servicioDomestico.aspx">Servicios domesticos.</a></li> 
         <li class="nav-top-1"><a href="servicioAsis.aspx">Servicios Asistenciales.</a></li> 
         <li class="nav-top-1"><a href="Lavanderia.aspx">Servicio de Lavanderia.</a></li> 
      </ul>
    </li>

    <li class="nav-top-1">
      <a>Presupuestos en Linea</a>
      <ul>
        <li class="nav-top-1"><a >Oficinas.</a>
          <ul>
            <li>
              <a href="oficinas1.aspx" style="
    color: #fff;
">Calcule Su Presuesto / Horas Necesarias</a>
            <a href="oficinas2.aspx" style="
    color: #fff;
">Calcule Su Presuesto / Horas a Contratar</a>
            </li>
          </ul>  
      </li>
        <li class="nav-top-1"><a >Comunidades.</a>
          <ul>
            <li>
              <a href="comunidades1.aspx" style="
    color: #fff;
">Calcule Su Presuesto / Horas Necesarias</a>
            <a href="comunidades2.aspx" style="
    color: #fff;
">Calcule Su Presuesto / Horas a Contratar</a>
            </li>
          </ul>  
    </li>  
      </ul>
    </li>
    
    <li class="nav-top-2">
      <a href="contacto.aspx">Contactanos</a>

    </li>

  </ul>

</div>