<div class="tel-hdr">
  <span class="skype_c2c_print_container notranslate">901 121 131</span>
  <span id="skype_c2c_container" class="skype_c2c_container notranslate" dir="ltr" tabindex="-1" onmouseover="SkypeClick2Call.MenuInjectionHandler.showMenu(this, event)" onmouseout="SkypeClick2Call.MenuInjectionHandler.hideMenu(this, event)" onclick="SkypeClick2Call.MenuInjectionHandler.makeCall(this, event)">
    <span class="skype_c2c_highlighting_inactive_common" dir="ltr">

      <span class="skype_c2c_textarea_span" id="free_num_ui">
        <img width="0" height="0" class="skype_c2c_logo_img" src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/call_skype_logo.png" />

       
      </span>
    </span>
  </span>
</div>