<link href="lin.css" rel="stylesheet" type="text/css">
<table style="width: 765px; text-align: left;">
<tr>
		<td height="20" colSpan="3"  class= "heather" id="tit2" style="text-align: center" title="Limpieza">SISTEMA DE LIMPIEZA BASADO EN LA SALUD Y RESPETO AL MEDIO AMBIENTE</td>
	</tr>
	<tr>
		<td width="338" colspan="" vAlign="center"  id="img" style="width: 327px" title="Limpieza"><a href="http://foxclean.es/"><img src="foxnature4.jpg" alt="" width="269" height="65" border="0"></a></td>
		<td height="65" align="center" vAlign="center"  id="img" style="width: 327px" title="Limpieza">
		
		</td>
		<td width="224" height="18" style="width: 118px">
		  <!-- Live2support.com tracking codes starts -->
		  <div id="l2s_trk" style="z-index:99;">
		    <a href="http://live2support.com" style="size:1px;">Live Support</a>
		    </div>
		  <script type="text/javascript">
				<!-- 
var l2s_lang='2743';var l2sinvite='Y'; var l2sinvwin='fw'; var l2sdly='60'; var l2sitop='center'; var l2sileft='center'; var l2s_pht=escape(location.protocol); if(l2s_pht.indexOf("http")==-1) l2s_pht='http:'; var dept="0"; function l2s_load() { document.write('<scr'+'ipt type="text/javaScr'+'ipt" src="'+unescape(l2s_pht)+'//live2support.com/js/lsjs1.php?stid=11990"  defer=true>'+'</scr'+'ipt>');  } 
l2s_load();  document.getElementById('l2s_trk').style.visibility='hidden'; //-->
			</script>
		  <!-- Live2support.com tracking codes closed -->
	    </td>
	</tr>
	<tr>
	  <td vAlign="top"  nowrap="" id="fon" style="width: 327px" title="Limpieza">Telefono: 902 121 131</td>
		<td height="18" colspan="2" align="center" vAlign="middle"  nowrap="" class="datos" style="text-align: center" title="Limpieza">E-MAIL: <A href="mailto:admin@foxclean.net">admin@foxclean.net</A></td>
  </tr>
</table>