<table id="menu"  cellspacing="0" cellpadding="0" width="100" border="0">
  <tr>
    <td title="Limpieza"  width="12" height="41"></td>
    <td title="Limpieza"  width="88" height="41">
      <p>
        <a href="segurTelecom.aspx">INICIO</a>
      </p>
    </td>
  </tr>  
    <tr>
    <td title="Limpieza"  width="12" height="41"></td>
    <td title="Limpieza"  width="88" height="41">
      SERVICIOS:
    </td>
  </tr>
  <tr>
    <td height="370" colspan="2" align="center" valign="top" title="Limpieza">
      <p></p>
      <p><a href="segurAntenas.aspx">ANTENAS</a></p>
<p>
        <a href="segurAntenas.aspx">
          <img src="antenna.png" width="38" height="38" border="0" alt="ANTENAS"/>
        </a>
      </p>
      <p>
        <a href="segurPorteros.aspx">PORTEROS</a>
      </p>
      <p>
        <a href="segurPorteros.aspx">
          <img src="porteros.electronicos.1.png" width="45" height="45" border="0" alt="PORTEROS"/>
        </a>
      </p>
      <p>
        <a href="segurSeguridad.aspx">SEGURIDAD</a>
      </p>
      <p>
        <a href="segurSeguridad.aspx">
          <img src="ico-seguridad.png" width="38" height="38" border="0" alt="SEGURIDAD"/>
        </a>
      </p>
    <p></p></td>
  </tr>

</table>
